### ISSUE TITLE
dashboard on new install contiously shows failure

### ISSUE THREAD

**Issue by KlavsKlavsen** [yetibot/yetibot-helm#7]
"Network error: JSON.parse: unexpected character at line 1 column 1 of the JSON data"
and log in pod says:
│ 21-04-28 10:44:36 yetibot-695c55dc8f-gs4lf INFO [ring.logger.timbre:13] - Starting :post /yetibot.kam.obmondo.com/graphql for 127.0.0.1 {"origin" "http://localhost:8080", "host" "localhost:8080", "user-agent" "Mozilla/5.0 (X11; U │
│ 21-04-28 10:44:36 yetibot-695c55dc8f-gs4lf INFO [ring.logger.timbre:13] -   \ - - - -  Params: {}                                                                                                                                     │
│ 21-04-28 10:44:36 yetibot-695c55dc8f-gs4lf INFO [ring.logger.timbre:13] - Finished :post /yetibot.kam.obmondo.com/graphql for 127.0.0.1 in (15 ms) Status: 404                                                                        │
│ 21-04-28 10:44:45 yetibot-695c55dc8f-gs4lf INFO [ring.logger.timbre:13] - Starting :post /yetibot.kam.obmondo.com/graphql for 127.0.0.1 {"origin" "http://localhost:8080", "host" "localhost:8080", "user-agent" "Mozilla/5.0 (X11; U │
│ 21-04-28 10:44:45 yetibot-695c55dc8f-gs4lf INFO [ring.logger.timbre:13] -   \ - - - -  Params: {}                              

even though I access /users or just /..
ideas?

**Comment by devth** [comment]
Are you running a yetibot at `localhost:8080`? You might need to [configure the URL](https://github.com/yetibot/core/blob/master/config/sample.env#L69).

For example, the [public Yetibot](https://public.yetibot.com) is configured with:

```
YB_URL=https://public.yetibot.com
```

**Comment by KlavsKlavsen** [comment]
I am setting YB_URL: "yetibot.kam.obmondo.com" - do I also need to enable ingress? I don't want yetibot to be accessed from outside - but that url is a public url..

**Comment by devth** [comment]
It would need to be at least accessible from your machine. It could be protected by a VPN for example. `yetibot-dashboard` relies on a [client-side GraphQL client](https://github.com/yetibot/yetibot-dashboard/blob/b6d1fac6d6649a63ddcaa6a26b7b40a0da8aa3ff/src/components/App.tsx#L49-L60) which makes requests directly from your browser.

**Comment by KlavsKlavsen** [comment]
I am currently just trying to access yetibot UI via kubectl port-forward - as it should not be accessible in general (afaik isn't necessary - as it connects out).. How do I get yetibot UI working (with port-forward) - without having to have a public URI? Can I just set it to YB_URL=http://localhost:8080 (and then portforward so thats the valid address?)

**Comment by devth** [comment]
Yep, that should work! As long as your web browser can reach the URL, which is should with port forwarding.

**Comment by KlavsKlavsen** [comment]
made a PR for a default - which works for port-forwarding.. so it'll work regardless of "traefik" or other ingress'es are up in a cluster
